version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 200
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 70
      statements: 40
    gocognit:
      min-complexity: 20
    gosec:
      excludes:
        - G115
    govet:
      enable-all: true
    lll:
      line-length: 200
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - funlen
          - lll
        path: _test\.go
    paths:
      - proto/*
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - proto/*
      - third_party$
      - builtin$
      - examples$
