run:
  timeout: 10m
  skip-dirs:
    - proto/*

linters:
  enable:
    - bodyclose
    # - deadcode // abandoned by owner
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - megacheck
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    # - rowserrcheck // disabled due to generics
    - staticcheck
    # - structcheck // abandoned by owner, disabled due to generics
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    # - varcheck // abandoned by owner
    - whitespace

linters-settings:
  dupl:
    threshold: 200
  exhaustive:
    default-signifies-exhaustive: true
  funlen:
    lines: 70
    statements: 40
  gocognit:
    min-complexity: 10
  govet:
    check-shadowing: true
  lll:
    line-length: 200

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - lll
