run:
  timeout: 10m
  skip-dirs:
    - proto/*

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - execinquery
    - exportloopref
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - lll
    - megacheck
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  dupl:
    threshold: 200
  exhaustive:
    default-signifies-exhaustive: true
  funlen:
    lines: 70
    statements: 40
  gocognit:
    min-complexity: 10
  govet:
    check-shadowing: true
  lll:
    line-length: 200

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - lll
