services:
  postgres:
    image: postgres:14.2-alpine
    container_name: arjuna-postgres
    volumes:
      - ${PWD}/tool/database:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 60s
      retries: 5
    networks:
      - arjuna

  db-migrate:
    image: migrate/migrate:v4.15.2
    container_name: arjuna-db-migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - $PWD:/app
    working_dir: /app
    entrypoint: [""]
    command: ["sh", "-c", "/app/tool/script/golang/migrate.sh"]
    networks:
      - arjuna

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    container_name: arjuna-keycloak
    depends_on:
      - postgres
      - sqlpad
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_DB_USERNAME=postgresuser
      - KC_DB_PASSWORD=postgrespassword
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_PORT=5432
      - KC_DB=postgres
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8080/health"]
      interval: 10s
      timeout: 60s
      retries: 5
    command: start-dev
    networks:
      - arjuna
  
  keycloak-init:
    image: golang:1.18
    container_name: arjuna-keycloak-init
    depends_on:
      keycloak:
        condition: service_healthy
    volumes:
      - $PWD:/app
    working_dir: /app/tool/script/keycloak
    entrypoint: [""]
    command: ["go", "run", "main.go"]
    networks:
      - arjuna
    
  sqlpad:
    image: sqlpad/sqlpad:6.10
    container_name: arjuna-sqlpad
    depends_on:
      - postgres
    environment:
      - SQLPAD_AUTH_DISABLED=true
      - SQLPAD_AUTH_DISABLED_DEFAULT_ROLE=admin
      - SQLPAD_DB_IN_MEMORY=true
      - SQLPAD_CONNECTIONS__user_postgres__name=Postgres - User
      - SQLPAD_CONNECTIONS__user_postgres__driver=postgres
      - SQLPAD_CONNECTIONS__user_postgres__host=postgres
      - SQLPAD_CONNECTIONS__user_postgres__port=5432
      - SQLPAD_CONNECTIONS__user_postgres__database=arjuna_user
      - SQLPAD_CONNECTIONS__user_postgres__username=postgresuser
      - SQLPAD_CONNECTIONS__user_postgres__password=postgrespassword
      - SQLPAD_CONNECTIONS__keycloak_postgres__name=Postgres - Keycloak
      - SQLPAD_CONNECTIONS__keycloak_postgres__driver=postgres
      - SQLPAD_CONNECTIONS__keycloak_postgres__host=postgres
      - SQLPAD_CONNECTIONS__keycloak_postgres__port=5432
      - SQLPAD_CONNECTIONS__keycloak_postgres__database=keycloak
      - SQLPAD_CONNECTIONS__keycloak_postgres__username=postgresuser
      - SQLPAD_CONNECTIONS__keycloak_postgres__password=postgrespassword
    ports:
      - 3000:3000
    networks:
      - arjuna

  blueprint:
    image: indrasaputra/arjuna-blueprint:latest
    container_name: arjuna-blueprint
    ports:
      - 4000:80
    networks:
      - arjuna

  # gateway:
  #   image: indrasaputra/arjuna-gateway:latest
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 8000:8000
  #   networks:
  #     - arjuna

  # user:
  #   image: indrasaputra/arjuna-user:latest
  #   depends_on:
  #     - postgres
  #     - keycloak
  #   ports:
  #     - 8001:8001
  #   env_file:
  #     - service/user/.env
  #   environment:
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PORT=5432
  #   networks:
  #     - arjuna

volumes:
  storage:

networks:
  arjuna:
