apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    url: http://jaeger:16686/
    access: proxy
    uid: jaeger
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags:
          - job
          - instance
