apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    url: http://tempo:3100
    access: proxy
    uid: tempo
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags:
          - job
          - instance
