// auth.proto defines service for auth.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/v1/auth.proto

package apiv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthErrorCode enumerates auth error code.
type AuthErrorCode int32

const (
	// Default enum code according to
	// https://medium.com/@akhaku/protobuf-definition-best-practices-87f281576f31.
	AuthErrorCode_AUTH_ERROR_CODE_UNSPECIFIED AuthErrorCode = 0
	// Unexpected behavior occured in system.
	AuthErrorCode_AUTH_ERROR_CODE_INTERNAL AuthErrorCode = 1
	// Mandatory field is empty.
	AuthErrorCode_AUTH_ERROR_CODE_EMPTY_FIELD AuthErrorCode = 2
	// Unauthorized.
	AuthErrorCode_AUTH_ERROR_CODE_UNAUTHORIZED AuthErrorCode = 3
	// Some arguments must be invalid.
	AuthErrorCode_AUTH_ERROR_CODE_INVALID_ARGUMENT AuthErrorCode = 4
	// Account instance is empty or nil.
	AuthErrorCode_AUTH_ERROR_CODE_EMPTY_ACCOUNT AuthErrorCode = 5
	// Account's email is invalid.
	AuthErrorCode_AUTH_ERROR_CODE_INVALID_EMAIL AuthErrorCode = 6
	// Account's password is invalid.
	AuthErrorCode_AUTH_ERROR_CODE_INVALID_PASSWORD AuthErrorCode = 7
	// Account already exists.
	// The uniqueness of an account is represented by email.
	AuthErrorCode_AUTH_ERROR_CODE_ALREADY_EXISTS AuthErrorCode = 8
	// Account's credential is invalid.
	AuthErrorCode_AUTH_ERROR_CODE_INVALID_CREDENTIAL AuthErrorCode = 9
	// Data is not found.
	AuthErrorCode_AUTH_ERROR_CODE_NOT_FOUND AuthErrorCode = 10
)

// Enum value maps for AuthErrorCode.
var (
	AuthErrorCode_name = map[int32]string{
		0:  "AUTH_ERROR_CODE_UNSPECIFIED",
		1:  "AUTH_ERROR_CODE_INTERNAL",
		2:  "AUTH_ERROR_CODE_EMPTY_FIELD",
		3:  "AUTH_ERROR_CODE_UNAUTHORIZED",
		4:  "AUTH_ERROR_CODE_INVALID_ARGUMENT",
		5:  "AUTH_ERROR_CODE_EMPTY_ACCOUNT",
		6:  "AUTH_ERROR_CODE_INVALID_EMAIL",
		7:  "AUTH_ERROR_CODE_INVALID_PASSWORD",
		8:  "AUTH_ERROR_CODE_ALREADY_EXISTS",
		9:  "AUTH_ERROR_CODE_INVALID_CREDENTIAL",
		10: "AUTH_ERROR_CODE_NOT_FOUND",
	}
	AuthErrorCode_value = map[string]int32{
		"AUTH_ERROR_CODE_UNSPECIFIED":        0,
		"AUTH_ERROR_CODE_INTERNAL":           1,
		"AUTH_ERROR_CODE_EMPTY_FIELD":        2,
		"AUTH_ERROR_CODE_UNAUTHORIZED":       3,
		"AUTH_ERROR_CODE_INVALID_ARGUMENT":   4,
		"AUTH_ERROR_CODE_EMPTY_ACCOUNT":      5,
		"AUTH_ERROR_CODE_INVALID_EMAIL":      6,
		"AUTH_ERROR_CODE_INVALID_PASSWORD":   7,
		"AUTH_ERROR_CODE_ALREADY_EXISTS":     8,
		"AUTH_ERROR_CODE_INVALID_CREDENTIAL": 9,
		"AUTH_ERROR_CODE_NOT_FOUND":          10,
	}
)

func (x AuthErrorCode) Enum() *AuthErrorCode {
	p := new(AuthErrorCode)
	*p = x
	return p
}

func (x AuthErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_auth_proto_enumTypes[0].Descriptor()
}

func (AuthErrorCode) Type() protoreflect.EnumType {
	return &file_api_v1_auth_proto_enumTypes[0]
}

func (x AuthErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthErrorCode.Descriptor instead.
func (AuthErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_auth_proto_rawDescGZIP(), []int{0}
}

// LoginRequest represents request for login.
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// credential represents credential for login.
	Credential    *Credential `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

// LoginResponse represents response from login.
type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data represents token.
	Data          *Token `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetData() *Token {
	if x != nil {
		return x.Data
	}
	return nil
}

// RegisterAccountRequest represents request for account registration.
type RegisterAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account represents account to register.
	Account       *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAccountRequest) Reset() {
	*x = RegisterAccountRequest{}
	mi := &file_api_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAccountRequest) ProtoMessage() {}

func (x *RegisterAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAccountRequest.ProtoReflect.Descriptor instead.
func (*RegisterAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterAccountRequest) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

// RegisterAccountResponse represents response for account registration.
type RegisterAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAccountResponse) Reset() {
	*x = RegisterAccountResponse{}
	mi := &file_api_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAccountResponse) ProtoMessage() {}

func (x *RegisterAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAccountResponse.ProtoReflect.Descriptor instead.
func (*RegisterAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_auth_proto_rawDescGZIP(), []int{3}
}

// Account represents account.
type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id represents unique id.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// user_id represents user's id.
	UserId string `protobuf:"bytes,2,opt,name=user_id,proto3" json:"user_id,omitempty"`
	// email represents user's email.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// password represents user's password
	Password      string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_api_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_api_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Account) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Credential represents login credential.
type Credential struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// email represents account's email.
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// password represents account's password.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credential) Reset() {
	*x = Credential{}
	mi := &file_api_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credential) ProtoMessage() {}

func (x *Credential) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credential.ProtoReflect.Descriptor instead.
func (*Credential) Descriptor() ([]byte, []int) {
	return file_api_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *Credential) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Credential) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Token represents token.
type Token struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AccessToken           string                 `protobuf:"bytes,1,opt,name=access_token,proto3" json:"access_token,omitempty"`
	RefreshToken          string                 `protobuf:"bytes,3,opt,name=refresh_token,proto3" json:"refresh_token,omitempty"`
	unknownFields         protoimpl.UnknownFields
	AccessTokenExpiresIn  uint32 `protobuf:"varint,2,opt,name=access_token_expires_in,proto3" json:"access_token_expires_in,omitempty"`
	RefreshTokenExpiresIn uint32 `protobuf:"varint,4,opt,name=refresh_token_expires_in,proto3" json:"refresh_token_expires_in,omitempty"`
	sizeCache             protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_api_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_api_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *Token) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Token) GetAccessTokenExpiresIn() uint32 {
	if x != nil {
		return x.AccessTokenExpiresIn
	}
	return 0
}

func (x *Token) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *Token) GetRefreshTokenExpiresIn() uint32 {
	if x != nil {
		return x.RefreshTokenExpiresIn
	}
	return 0
}

// AuthError represents message for any error happening in auth service.
type AuthError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	ErrorCode     AuthErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=api.v1.AuthErrorCode" json:"error_code,omitempty"`
	sizeCache     protoimpl.SizeCache
}

func (x *AuthError) Reset() {
	*x = AuthError{}
	mi := &file_api_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthError) ProtoMessage() {}

func (x *AuthError) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthError.ProtoReflect.Descriptor instead.
func (*AuthError) Descriptor() ([]byte, []int) {
	return file_api_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *AuthError) GetErrorCode() AuthErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return AuthErrorCode_AUTH_ERROR_CODE_UNSPECIFIED
}

var File_api_v1_auth_proto protoreflect.FileDescriptor

const file_api_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x11api/v1/auth.proto\x12\x06api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"G\n" +
	"\fLoginRequest\x127\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x12.api.v1.CredentialB\x03\xe0A\x02R\n" +
	"credential\"2\n" +
	"\rLoginResponse\x12!\n" +
	"\x04data\x18\x01 \x01(\v2\r.api.v1.TokenR\x04data\"C\n" +
	"\x16RegisterAccountRequest\x12)\n" +
	"\aaccount\x18\x01 \x01(\v2\x0f.api.v1.AccountR\aaccount\"\x19\n" +
	"\x17RegisterAccountResponse\"\xd8\x02\n" +
	"\aAccount\x12A\n" +
	"\x02id\x18\x01 \x01(\tB1\x92A(J&\"01917a0c-475e-7d4a-9ec1-a56d14d78569\"\xe0A\x02\xe0A\x03R\x02id\x12\\\n" +
	"\auser_id\x18\x02 \x01(\tBB\x92A<2\tUser's idJ&\"01917a0c-cdfe-7696-9259-1c9821c8fd73\"\xa2\x02\x06string\xe0A\x02R\auser_id\x12a\n" +
	"\x05email\x18\x03 \x01(\tBK\x92AE2\fUser's emailJ\x12\"email@domain.com\"\x8a\x01 ^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$\xe0A\x02R\x05email\x12I\n" +
	"\bpassword\x18\x04 \x01(\tB-\x92A*2\x0fUser's passwordJ\x0e\"weakPassword\"\xa2\x02\x06stringR\bpassword\"\xbd\x01\n" +
	"\n" +
	"Credential\x12a\n" +
	"\x05email\x18\x01 \x01(\tBK\x92AE2\fUser's emailJ\x12\"email@domain.com\"\x8a\x01 ^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$\xe0A\x02R\x05email\x12L\n" +
	"\bpassword\x18\x02 \x01(\tB0\x92A*2\x0fUser's passwordJ\x0e\"weakPassword\"\xa2\x02\x06string\xe0A\x02R\bpassword\"\xe7\x01\n" +
	"\x05Token\x12*\n" +
	"\faccess_token\x18\x01 \x01(\tB\x06\xe0A\x02\xe0A\x03R\faccess_token\x12@\n" +
	"\x17access_token_expires_in\x18\x02 \x01(\rB\x06\xe0A\x02\xe0A\x03R\x17access_token_expires_in\x12,\n" +
	"\rrefresh_token\x18\x03 \x01(\tB\x06\xe0A\x02\xe0A\x03R\rrefresh_token\x12B\n" +
	"\x18refresh_token_expires_in\x18\x04 \x01(\rB\x06\xe0A\x02\xe0A\x03R\x18refresh_token_expires_in\"A\n" +
	"\tAuthError\x124\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x15.api.v1.AuthErrorCodeR\terrorCode*\x8e\x03\n" +
	"\rAuthErrorCode\x12\x1f\n" +
	"\x1bAUTH_ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18AUTH_ERROR_CODE_INTERNAL\x10\x01\x12\x1f\n" +
	"\x1bAUTH_ERROR_CODE_EMPTY_FIELD\x10\x02\x12 \n" +
	"\x1cAUTH_ERROR_CODE_UNAUTHORIZED\x10\x03\x12$\n" +
	" AUTH_ERROR_CODE_INVALID_ARGUMENT\x10\x04\x12!\n" +
	"\x1dAUTH_ERROR_CODE_EMPTY_ACCOUNT\x10\x05\x12!\n" +
	"\x1dAUTH_ERROR_CODE_INVALID_EMAIL\x10\x06\x12$\n" +
	" AUTH_ERROR_CODE_INVALID_PASSWORD\x10\a\x12\"\n" +
	"\x1eAUTH_ERROR_CODE_ALREADY_EXISTS\x10\b\x12&\n" +
	"\"AUTH_ERROR_CODE_INVALID_CREDENTIAL\x10\t\x12\x1d\n" +
	"\x19AUTH_ERROR_CODE_NOT_FOUND\x10\n" +
	"2\x8a\x02\n" +
	"\vAuthService\x12h\n" +
	"\x05Login\x12\x14.api.v1.LoginRequest\x1a\x15.api.v1.LoginResponse\"2\x92A\r\n" +
	"\x04Auth*\x05Login\x82\xd3\xe4\x93\x02\x1c:\n" +
	"credential\"\x0e/v1/auth/login\x12T\n" +
	"\x0fRegisterAccount\x12\x1e.api.v1.RegisterAccountRequest\x1a\x1f.api.v1.RegisterAccountResponse\"\x00\x1a;\x92A8\x126This service provides all use cases to work with auth.B\x8d\x02\x92A\xcf\x01\x12\x95\x01\n" +
	"\bAuth API\"0\n" +
	"\rIndra Saputra\x12\x1fhttps://github.com/indrasaputra*P\n" +
	"\x14BSD 3-Clause License\x128https://github.com/indrasaputra/arjuna/blob/main/LICENSE2\x051.0.0\x1a\x0elocalhost:8000*\x01\x012\x10application/json:\x10application/jsonZ8github.com/indrasaputra/arjuna/service/auth/api/v1;apiv1b\x06proto3"

var (
	file_api_v1_auth_proto_rawDescOnce sync.Once
	file_api_v1_auth_proto_rawDescData []byte
)

func file_api_v1_auth_proto_rawDescGZIP() []byte {
	file_api_v1_auth_proto_rawDescOnce.Do(func() {
		file_api_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_auth_proto_rawDesc), len(file_api_v1_auth_proto_rawDesc)))
	})
	return file_api_v1_auth_proto_rawDescData
}

var file_api_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_v1_auth_proto_goTypes = []any{
	(AuthErrorCode)(0),              // 0: api.v1.AuthErrorCode
	(*LoginRequest)(nil),            // 1: api.v1.LoginRequest
	(*LoginResponse)(nil),           // 2: api.v1.LoginResponse
	(*RegisterAccountRequest)(nil),  // 3: api.v1.RegisterAccountRequest
	(*RegisterAccountResponse)(nil), // 4: api.v1.RegisterAccountResponse
	(*Account)(nil),                 // 5: api.v1.Account
	(*Credential)(nil),              // 6: api.v1.Credential
	(*Token)(nil),                   // 7: api.v1.Token
	(*AuthError)(nil),               // 8: api.v1.AuthError
}
var file_api_v1_auth_proto_depIdxs = []int32{
	6, // 0: api.v1.LoginRequest.credential:type_name -> api.v1.Credential
	7, // 1: api.v1.LoginResponse.data:type_name -> api.v1.Token
	5, // 2: api.v1.RegisterAccountRequest.account:type_name -> api.v1.Account
	0, // 3: api.v1.AuthError.error_code:type_name -> api.v1.AuthErrorCode
	1, // 4: api.v1.AuthService.Login:input_type -> api.v1.LoginRequest
	3, // 5: api.v1.AuthService.RegisterAccount:input_type -> api.v1.RegisterAccountRequest
	2, // 6: api.v1.AuthService.Login:output_type -> api.v1.LoginResponse
	4, // 7: api.v1.AuthService.RegisterAccount:output_type -> api.v1.RegisterAccountResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_auth_proto_init() }
func file_api_v1_auth_proto_init() {
	if File_api_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_auth_proto_rawDesc), len(file_api_v1_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_auth_proto_goTypes,
		DependencyIndexes: file_api_v1_auth_proto_depIdxs,
		EnumInfos:         file_api_v1_auth_proto_enumTypes,
		MessageInfos:      file_api_v1_auth_proto_msgTypes,
	}.Build()
	File_api_v1_auth_proto = out.File
	file_api_v1_auth_proto_goTypes = nil
	file_api_v1_auth_proto_depIdxs = nil
}
