// transaction.proto defines service for transaction.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/v1/transaction.proto

package apiv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransactionErrorCode enumerates transaction error code.
type TransactionErrorCode int32

const (
	// Default enum code according to
	// https://medium.com/@akhaku/protobuf-definition-best-practices-87f281576f31.
	TransactionErrorCode_TRANSACTION_ERROR_CODE_UNSPECIFIED TransactionErrorCode = 0
	// Unexpected behavior occured in system.
	TransactionErrorCode_TRANSACTION_ERROR_CODE_INTERNAL TransactionErrorCode = 1
	// Transaction already exists.
	TransactionErrorCode_TRANSACTION_ERROR_CODE_ALREADY_EXISTS TransactionErrorCode = 2
	// Transaction instance is nil or empty.
	TransactionErrorCode_TRANSACTION_ERROR_CODE_EMPTY_TRANSACTION TransactionErrorCode = 3
	// Sender is invalid.
	TransactionErrorCode_TRANSACTION_ERROR_CODE_INVALID_SENDER TransactionErrorCode = 4
	// Receiver is invalid.
	TransactionErrorCode_TRANSACTION_ERROR_CODE_INVALID_RECEIVER TransactionErrorCode = 5
	// Amount must be numeric and greater than zero.
	TransactionErrorCode_TRANSACTION_ERROR_CODE_INVALID_AMOUNT TransactionErrorCode = 6
	// Idempotency key is missing.
	TransactionErrorCode_TRANSACTION_ERROR_CODE_MISSING_IDEMPOTENCY_KEY TransactionErrorCode = 7
)

// Enum value maps for TransactionErrorCode.
var (
	TransactionErrorCode_name = map[int32]string{
		0: "TRANSACTION_ERROR_CODE_UNSPECIFIED",
		1: "TRANSACTION_ERROR_CODE_INTERNAL",
		2: "TRANSACTION_ERROR_CODE_ALREADY_EXISTS",
		3: "TRANSACTION_ERROR_CODE_EMPTY_TRANSACTION",
		4: "TRANSACTION_ERROR_CODE_INVALID_SENDER",
		5: "TRANSACTION_ERROR_CODE_INVALID_RECEIVER",
		6: "TRANSACTION_ERROR_CODE_INVALID_AMOUNT",
		7: "TRANSACTION_ERROR_CODE_MISSING_IDEMPOTENCY_KEY",
	}
	TransactionErrorCode_value = map[string]int32{
		"TRANSACTION_ERROR_CODE_UNSPECIFIED":             0,
		"TRANSACTION_ERROR_CODE_INTERNAL":                1,
		"TRANSACTION_ERROR_CODE_ALREADY_EXISTS":          2,
		"TRANSACTION_ERROR_CODE_EMPTY_TRANSACTION":       3,
		"TRANSACTION_ERROR_CODE_INVALID_SENDER":          4,
		"TRANSACTION_ERROR_CODE_INVALID_RECEIVER":        5,
		"TRANSACTION_ERROR_CODE_INVALID_AMOUNT":          6,
		"TRANSACTION_ERROR_CODE_MISSING_IDEMPOTENCY_KEY": 7,
	}
)

func (x TransactionErrorCode) Enum() *TransactionErrorCode {
	p := new(TransactionErrorCode)
	*p = x
	return p
}

func (x TransactionErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_transaction_proto_enumTypes[0].Descriptor()
}

func (TransactionErrorCode) Type() protoreflect.EnumType {
	return &file_api_v1_transaction_proto_enumTypes[0]
}

func (x TransactionErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionErrorCode.Descriptor instead.
func (TransactionErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_transaction_proto_rawDescGZIP(), []int{0}
}

// CreateTransactionRequest represents request for create transaction.
type CreateTransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// transaction represents transaction data.
	Transaction   *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_api_v1_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// CreateTransactionResponse represents response from create transaction.
type CreateTransactionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data represents transaction.
	Data          *Transaction `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_api_v1_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransactionResponse) GetData() *Transaction {
	if x != nil {
		return x.Data
	}
	return nil
}

// Transaction represents transaction.
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id represents unique id.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// sender_id represents sender's id.
	SenderId string `protobuf:"bytes,2,opt,name=sender_id,proto3" json:"sender_id,omitempty"`
	// receiver_id represents receiver's id.
	ReceiverId string `protobuf:"bytes,3,opt,name=receiver_id,proto3" json:"receiver_id,omitempty"`
	// amount represents amount.
	Amount string `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// created_at represents when the transaction was created.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_api_v1_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_api_v1_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Transaction) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *Transaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// TransactionError represents message for any error happening in transaction service.
type TransactionError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	ErrorCode     TransactionErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=api.v1.TransactionErrorCode" json:"error_code,omitempty"`
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionError) Reset() {
	*x = TransactionError{}
	mi := &file_api_v1_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionError) ProtoMessage() {}

func (x *TransactionError) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionError.ProtoReflect.Descriptor instead.
func (*TransactionError) Descriptor() ([]byte, []int) {
	return file_api_v1_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionError) GetErrorCode() TransactionErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return TransactionErrorCode_TRANSACTION_ERROR_CODE_UNSPECIFIED
}

var File_api_v1_transaction_proto protoreflect.FileDescriptor

const file_api_v1_transaction_proto_rawDesc = "" +
	"\n" +
	"\x18api/v1/transaction.proto\x12\x06api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"Q\n" +
	"\x18CreateTransactionRequest\x125\n" +
	"\vtransaction\x18\x01 \x01(\v2\x13.api.v1.TransactionR\vtransaction\"D\n" +
	"\x19CreateTransactionResponse\x12'\n" +
	"\x04data\x18\x01 \x01(\v2\x13.api.v1.TransactionR\x04data\"\x9c\x03\n" +
	"\vTransaction\x12>\n" +
	"\x02id\x18\x01 \x01(\tB.\x92A(J&\"01917a0c-cdfe-7d3c-b0fc-ea83671bf6d9\"\xe0A\x03R\x02id\x12d\n" +
	"\tsender_id\x18\x02 \x01(\tBF\x92AC2\x19Transaction's sender's idJ&\"01917a0c-cdfe-7ce9-a9aa-a921cfd6c289\"R\tsender_id\x12j\n" +
	"\vreceiver_id\x18\x03 \x01(\tBH\x92AE2\x1bTransaction's receiver's idJ&\"01917a0c-cdfe-7f72-9b8f-12c3480d5baf\"R\vreceiver_id\x12:\n" +
	"\x06amount\x18\x04 \x01(\tB\"\x92A\x1f2\x14Transaction's amountJ\a\"10.23\"R\x06amount\x12?\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"created_at\"O\n" +
	"\x10TransactionError\x12;\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x1c.api.v1.TransactionErrorCodeR\terrorCode*\xf3\x02\n" +
	"\x14TransactionErrorCode\x12&\n" +
	"\"TRANSACTION_ERROR_CODE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fTRANSACTION_ERROR_CODE_INTERNAL\x10\x01\x12)\n" +
	"%TRANSACTION_ERROR_CODE_ALREADY_EXISTS\x10\x02\x12,\n" +
	"(TRANSACTION_ERROR_CODE_EMPTY_TRANSACTION\x10\x03\x12)\n" +
	"%TRANSACTION_ERROR_CODE_INVALID_SENDER\x10\x04\x12+\n" +
	"'TRANSACTION_ERROR_CODE_INVALID_RECEIVER\x10\x05\x12)\n" +
	"%TRANSACTION_ERROR_CODE_INVALID_AMOUNT\x10\x06\x122\n" +
	".TRANSACTION_ERROR_CODE_MISSING_IDEMPOTENCY_KEY\x10\a2\xb4\x02\n" +
	"\x19TransactionCommandService\x12\xd2\x01\n" +
	"\x11CreateTransaction\x12 .api.v1.CreateTransactionRequest\x1a!.api.v1.CreateTransactionResponse\"x\x92AP\n" +
	"\vTransaction*\x11CreateTransactionr.\n" +
	"\x13\n" +
	"\rAuthorization\x18\x01(\x01\n" +
	"\x17\n" +
	"\x11X-Idempotency-Key\x18\x01(\x01\x82\xd3\xe4\x93\x02\x1f:\vtransaction\"\x10/v1/transactions\x1aB\x92A?\x12=This service provides all use cases to work with transaction.B\x9b\x02\x92A\xd6\x01\x12\x9c\x01\n" +
	"\x0fTransaction API\"0\n" +
	"\rIndra Saputra\x12\x1fhttps://github.com/indrasaputra*P\n" +
	"\x14BSD 3-Clause License\x128https://github.com/indrasaputra/arjuna/blob/main/LICENSE2\x051.0.0\x1a\x0elocalhost:8000*\x01\x012\x10application/json:\x10application/jsonZ?github.com/indrasaputra/arjuna/service/transaction/api/v1;apiv1b\x06proto3"

var (
	file_api_v1_transaction_proto_rawDescOnce sync.Once
	file_api_v1_transaction_proto_rawDescData []byte
)

func file_api_v1_transaction_proto_rawDescGZIP() []byte {
	file_api_v1_transaction_proto_rawDescOnce.Do(func() {
		file_api_v1_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_transaction_proto_rawDesc), len(file_api_v1_transaction_proto_rawDesc)))
	})
	return file_api_v1_transaction_proto_rawDescData
}

var file_api_v1_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v1_transaction_proto_goTypes = []any{
	(TransactionErrorCode)(0),         // 0: api.v1.TransactionErrorCode
	(*CreateTransactionRequest)(nil),  // 1: api.v1.CreateTransactionRequest
	(*CreateTransactionResponse)(nil), // 2: api.v1.CreateTransactionResponse
	(*Transaction)(nil),               // 3: api.v1.Transaction
	(*TransactionError)(nil),          // 4: api.v1.TransactionError
	(*timestamppb.Timestamp)(nil),     // 5: google.protobuf.Timestamp
}
var file_api_v1_transaction_proto_depIdxs = []int32{
	3, // 0: api.v1.CreateTransactionRequest.transaction:type_name -> api.v1.Transaction
	3, // 1: api.v1.CreateTransactionResponse.data:type_name -> api.v1.Transaction
	5, // 2: api.v1.Transaction.created_at:type_name -> google.protobuf.Timestamp
	0, // 3: api.v1.TransactionError.error_code:type_name -> api.v1.TransactionErrorCode
	1, // 4: api.v1.TransactionCommandService.CreateTransaction:input_type -> api.v1.CreateTransactionRequest
	2, // 5: api.v1.TransactionCommandService.CreateTransaction:output_type -> api.v1.CreateTransactionResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_transaction_proto_init() }
func file_api_v1_transaction_proto_init() {
	if File_api_v1_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_transaction_proto_rawDesc), len(file_api_v1_transaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_transaction_proto_goTypes,
		DependencyIndexes: file_api_v1_transaction_proto_depIdxs,
		EnumInfos:         file_api_v1_transaction_proto_enumTypes,
		MessageInfos:      file_api_v1_transaction_proto_msgTypes,
	}.Build()
	File_api_v1_transaction_proto = out.File
	file_api_v1_transaction_proto_goTypes = nil
	file_api_v1_transaction_proto_depIdxs = nil
}
