// user.proto defines service for user.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/v1/user.proto

package apiv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserOutboxStatus enumerates user outbox status code.
type UserOutboxStatus int32

const (
	// Default enum code according to
	// https://medium.com/@akhaku/protobuf-definition-best-practices-87f281576f31.
	UserOutboxStatus_USER_OUTBOX_STATUS_UNSPECIFIED UserOutboxStatus = 0
	// Record ready to be picked up.
	UserOutboxStatus_USER_OUTBOX_STATUS_READY UserOutboxStatus = 1
	// Record is being processed to be sent to server.
	UserOutboxStatus_USER_OUTBOX_STATUS_PROCESSED UserOutboxStatus = 2
	// Record is successfully delivered to server.
	UserOutboxStatus_USER_OUTBOX_STATUS_DELIVERED UserOutboxStatus = 3
	// Record is failed to be processed.
	UserOutboxStatus_USER_OUTBOX_STATUS_FAILED UserOutboxStatus = 4
)

// Enum value maps for UserOutboxStatus.
var (
	UserOutboxStatus_name = map[int32]string{
		0: "USER_OUTBOX_STATUS_UNSPECIFIED",
		1: "USER_OUTBOX_STATUS_READY",
		2: "USER_OUTBOX_STATUS_PROCESSED",
		3: "USER_OUTBOX_STATUS_DELIVERED",
		4: "USER_OUTBOX_STATUS_FAILED",
	}
	UserOutboxStatus_value = map[string]int32{
		"USER_OUTBOX_STATUS_UNSPECIFIED": 0,
		"USER_OUTBOX_STATUS_READY":       1,
		"USER_OUTBOX_STATUS_PROCESSED":   2,
		"USER_OUTBOX_STATUS_DELIVERED":   3,
		"USER_OUTBOX_STATUS_FAILED":      4,
	}
)

func (x UserOutboxStatus) Enum() *UserOutboxStatus {
	p := new(UserOutboxStatus)
	*p = x
	return p
}

func (x UserOutboxStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserOutboxStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_user_proto_enumTypes[0].Descriptor()
}

func (UserOutboxStatus) Type() protoreflect.EnumType {
	return &file_api_v1_user_proto_enumTypes[0]
}

func (x UserOutboxStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserOutboxStatus.Descriptor instead.
func (UserOutboxStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{0}
}

// UserErrorCode enumerates user error code.
type UserErrorCode int32

const (
	// Default enum code according to
	// https://medium.com/@akhaku/protobuf-definition-best-practices-87f281576f31.
	UserErrorCode_USER_ERROR_CODE_UNSPECIFIED UserErrorCode = 0
	// Unexpected behavior occured in system.
	UserErrorCode_USER_ERROR_CODE_INTERNAL UserErrorCode = 1
	// User instance is empty or nil.
	UserErrorCode_USER_ERROR_CODE_EMPTY_USER UserErrorCode = 2
	// User already exists.
	// The uniqueness of a user is represented by email.
	UserErrorCode_USER_ERROR_CODE_ALREADY_EXISTS UserErrorCode = 3
	// User's name is invalid.
	// Allowed characters are alphabet only.
	UserErrorCode_USER_ERROR_CODE_INVALID_NAME UserErrorCode = 4
	// User's email is invalid.
	UserErrorCode_USER_ERROR_CODE_INVALID_EMAIL UserErrorCode = 5
	// User not found.
	UserErrorCode_USER_ERROR_CODE_NOT_FOUND UserErrorCode = 6
	// Idempotency key is missing.
	UserErrorCode_USER_ERROR_CODE_MISSING_IDEMPOTENCY_KEY UserErrorCode = 7
)

// Enum value maps for UserErrorCode.
var (
	UserErrorCode_name = map[int32]string{
		0: "USER_ERROR_CODE_UNSPECIFIED",
		1: "USER_ERROR_CODE_INTERNAL",
		2: "USER_ERROR_CODE_EMPTY_USER",
		3: "USER_ERROR_CODE_ALREADY_EXISTS",
		4: "USER_ERROR_CODE_INVALID_NAME",
		5: "USER_ERROR_CODE_INVALID_EMAIL",
		6: "USER_ERROR_CODE_NOT_FOUND",
		7: "USER_ERROR_CODE_MISSING_IDEMPOTENCY_KEY",
	}
	UserErrorCode_value = map[string]int32{
		"USER_ERROR_CODE_UNSPECIFIED":             0,
		"USER_ERROR_CODE_INTERNAL":                1,
		"USER_ERROR_CODE_EMPTY_USER":              2,
		"USER_ERROR_CODE_ALREADY_EXISTS":          3,
		"USER_ERROR_CODE_INVALID_NAME":            4,
		"USER_ERROR_CODE_INVALID_EMAIL":           5,
		"USER_ERROR_CODE_NOT_FOUND":               6,
		"USER_ERROR_CODE_MISSING_IDEMPOTENCY_KEY": 7,
	}
)

func (x UserErrorCode) Enum() *UserErrorCode {
	p := new(UserErrorCode)
	*p = x
	return p
}

func (x UserErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_user_proto_enumTypes[1].Descriptor()
}

func (UserErrorCode) Type() protoreflect.EnumType {
	return &file_api_v1_user_proto_enumTypes[1]
}

func (x UserErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserErrorCode.Descriptor instead.
func (UserErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{1}
}

// RegisterUserRequest represents request for register user.
type RegisterUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user represents user data.
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_api_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// RegisterUserResponse represents response from register user.
type RegisterUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data represents user.
	Data          *User `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_api_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserResponse) GetData() *User {
	if x != nil {
		return x.Data
	}
	return nil
}

// DeleteUserRequest represents request for delete user.
type DeleteUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id represents user's id.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_api_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteUserResponse represents response from delete user.
type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_api_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{3}
}

// GetAllUsersRequest represents request for get all users.
type GetAllUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	Limit         uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersRequest) Reset() {
	*x = GetAllUsersRequest{}
	mi := &file_api_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersRequest) ProtoMessage() {}

func (x *GetAllUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersRequest.ProtoReflect.Descriptor instead.
func (*GetAllUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllUsersRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetAllUsersResponse represents response from get all users.
type GetAllUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data represents an array of user data.
	Data          []*User `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersResponse) Reset() {
	*x = GetAllUsersResponse{}
	mi := &file_api_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersResponse) ProtoMessage() {}

func (x *GetAllUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersResponse.ProtoReflect.Descriptor instead.
func (*GetAllUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllUsersResponse) GetData() []*User {
	if x != nil {
		return x.Data
	}
	return nil
}

// User represents a user data.
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id represents a user's id.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// email represents a user's email.
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// password represents the user's password.
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// name represents a user's name.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// created_at represents when the user was registered.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,proto3" json:"created_at,omitempty"`
	// updated_at represents when the user was last updated.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// UserOutbox represents a user outbox data.
type UserOutbox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *User                  `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	Status        UserOutboxStatus `protobuf:"varint,2,opt,name=status,proto3,enum=api.v1.UserOutboxStatus" json:"status,omitempty"`
	sizeCache     protoimpl.SizeCache
}

func (x *UserOutbox) Reset() {
	*x = UserOutbox{}
	mi := &file_api_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOutbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOutbox) ProtoMessage() {}

func (x *UserOutbox) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOutbox.ProtoReflect.Descriptor instead.
func (*UserOutbox) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserOutbox) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserOutbox) GetStatus() UserOutboxStatus {
	if x != nil {
		return x.Status
	}
	return UserOutboxStatus_USER_OUTBOX_STATUS_UNSPECIFIED
}

func (x *UserOutbox) GetPayload() *User {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UserOutbox) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserOutbox) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// UserError represents message for any error happening in user.
type UserError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	ErrorCode     UserErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=api.v1.UserErrorCode" json:"error_code,omitempty"`
	sizeCache     protoimpl.SizeCache
}

func (x *UserError) Reset() {
	*x = UserError{}
	mi := &file_api_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserError) ProtoMessage() {}

func (x *UserError) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserError.ProtoReflect.Descriptor instead.
func (*UserError) Descriptor() ([]byte, []int) {
	return file_api_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserError) GetErrorCode() UserErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return UserErrorCode_USER_ERROR_CODE_UNSPECIFIED
}

var File_api_v1_user_proto protoreflect.FileDescriptor

const file_api_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x11api/v1/user.proto\x12\x06api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"<\n" +
	"\x13RegisterUserRequest\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\f.api.v1.UserB\x03\xe0A\x02R\x04user\"8\n" +
	"\x14RegisterUserResponse\x12 \n" +
	"\x04data\x18\x01 \x01(\v2\f.api.v1.UserR\x04data\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteUserResponse\"*\n" +
	"\x12GetAllUsersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\"7\n" +
	"\x13GetAllUsersResponse\x12 \n" +
	"\x04data\x18\x01 \x03(\v2\f.api.v1.UserR\x04data\"\xc3\x03\n" +
	"\x04User\x12>\n" +
	"\x02id\x18\x01 \x01(\tB.\x92A(J&\"01917a0c-cdfe-7e4f-9692-635eb6a6f358\"\xe0A\x03R\x02id\x12g\n" +
	"\x05email\x18\x02 \x01(\tBQ\x92AK2\fuser's emailJ\x10\"first@user.com\"\x8a\x01 ^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$\xd2\x01\x05email\xe0A\x02R\x05email\x12S\n" +
	"\bpassword\x18\x03 \x01(\tB7\x92A.2\x0fuser's passwordJ\x12\"WEAKpassword123?\"\xa2\x02\x06string\xe0A\x02\xe0A\x04R\bpassword\x12;\n" +
	"\x04name\x18\x04 \x01(\tB'\x92A!2\vuser's nameJ\f\"First User\"x\xff\x01\x80\x01\x01\xe0A\x02R\x04name\x12?\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"created_at\x12?\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updated_at\"\xa8\x02\n" +
	"\n" +
	"UserOutbox\x12>\n" +
	"\x02id\x18\x01 \x01(\tB.\x92A(J&\"01917a0c-cdfe-7cf5-afc1-620959bf240e\"\xe0A\x03R\x02id\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.api.v1.UserOutboxStatusR\x06status\x12&\n" +
	"\apayload\x18\x03 \x01(\v2\f.api.v1.UserR\apayload\x12?\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"created_at\x12?\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updated_at\"A\n" +
	"\tUserError\x124\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x15.api.v1.UserErrorCodeR\terrorCode*\xb7\x01\n" +
	"\x10UserOutboxStatus\x12\"\n" +
	"\x1eUSER_OUTBOX_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18USER_OUTBOX_STATUS_READY\x10\x01\x12 \n" +
	"\x1cUSER_OUTBOX_STATUS_PROCESSED\x10\x02\x12 \n" +
	"\x1cUSER_OUTBOX_STATUS_DELIVERED\x10\x03\x12\x1d\n" +
	"\x19USER_OUTBOX_STATUS_FAILED\x10\x04*\xa3\x02\n" +
	"\rUserErrorCode\x12\x1f\n" +
	"\x1bUSER_ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18USER_ERROR_CODE_INTERNAL\x10\x01\x12\x1e\n" +
	"\x1aUSER_ERROR_CODE_EMPTY_USER\x10\x02\x12\"\n" +
	"\x1eUSER_ERROR_CODE_ALREADY_EXISTS\x10\x03\x12 \n" +
	"\x1cUSER_ERROR_CODE_INVALID_NAME\x10\x04\x12!\n" +
	"\x1dUSER_ERROR_CODE_INVALID_EMAIL\x10\x05\x12\x1d\n" +
	"\x19USER_ERROR_CODE_NOT_FOUND\x10\x06\x12+\n" +
	"'USER_ERROR_CODE_MISSING_IDEMPOTENCY_KEY\x10\a2\xcb\x02\n" +
	"\x12UserCommandService\x12\x9d\x01\n" +
	"\fRegisterUser\x12\x1b.api.v1.RegisterUserRequest\x1a\x1c.api.v1.RegisterUserResponse\"R\x92A/\n" +
	"\x04User*\fRegisterUserr\x19\n" +
	"\x17\n" +
	"\x11X-Idempotency-Key\x18\x01(\x01\x82\xd3\xe4\x93\x02\x1a:\x04user\"\x12/v1/users/register\x1a\x94\x01\x92A\x90\x01\x12\x8d\x01This service provides basic command or state-changing use cases to work with user.A user is represented by an email as its unique identifier.2\xc0\x01\n" +
	"\x1aUserCommandInternalService\x12E\n" +
	"\n" +
	"DeleteUser\x12\x19.api.v1.DeleteUserRequest\x1a\x1a.api.v1.DeleteUserResponse\"\x00\x1a[\x92AX\x12VIt is the same as UserCommand but should be used internally and not exposed to public.2\xf3\x01\n" +
	"\x10UserQueryService\x12\x86\x01\n" +
	"\vGetAllUsers\x12\x1a.api.v1.GetAllUsersRequest\x1a\x1b.api.v1.GetAllUsersResponse\">\x92A*\n" +
	"\x04User*\vGetAllUsersr\x15\n" +
	"\x13\n" +
	"\rAuthorization\x18\x01(\x01\x82\xd3\xe4\x93\x02\v\x12\t/v1/users\x1aV\x92AS\x12QThis service provides basic query or data-retrieving use cases to work with user.B\x85\x02\x92A\xcf\x01\x12\x95\x01\n" +
	"\bUser API\"0\n" +
	"\rIndra Saputra\x12\x1fhttps://github.com/indrasaputra*P\n" +
	"\x14BSD 3-Clause License\x128https://github.com/indrasaputra/arjuna/blob/main/LICENSE2\x051.0.0\x1a\x0elocalhost:8000*\x01\x012\x10application/json:\x10application/jsonZ0github.com/indrasaputra/arjuna/user/api/v1;apiv1b\x06proto3"

var (
	file_api_v1_user_proto_rawDescOnce sync.Once
	file_api_v1_user_proto_rawDescData []byte
)

func file_api_v1_user_proto_rawDescGZIP() []byte {
	file_api_v1_user_proto_rawDescOnce.Do(func() {
		file_api_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_user_proto_rawDesc), len(file_api_v1_user_proto_rawDesc)))
	})
	return file_api_v1_user_proto_rawDescData
}

var file_api_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_v1_user_proto_goTypes = []any{
	(UserOutboxStatus)(0),         // 0: api.v1.UserOutboxStatus
	(UserErrorCode)(0),            // 1: api.v1.UserErrorCode
	(*RegisterUserRequest)(nil),   // 2: api.v1.RegisterUserRequest
	(*RegisterUserResponse)(nil),  // 3: api.v1.RegisterUserResponse
	(*DeleteUserRequest)(nil),     // 4: api.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),    // 5: api.v1.DeleteUserResponse
	(*GetAllUsersRequest)(nil),    // 6: api.v1.GetAllUsersRequest
	(*GetAllUsersResponse)(nil),   // 7: api.v1.GetAllUsersResponse
	(*User)(nil),                  // 8: api.v1.User
	(*UserOutbox)(nil),            // 9: api.v1.UserOutbox
	(*UserError)(nil),             // 10: api.v1.UserError
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_api_v1_user_proto_depIdxs = []int32{
	8,  // 0: api.v1.RegisterUserRequest.user:type_name -> api.v1.User
	8,  // 1: api.v1.RegisterUserResponse.data:type_name -> api.v1.User
	8,  // 2: api.v1.GetAllUsersResponse.data:type_name -> api.v1.User
	11, // 3: api.v1.User.created_at:type_name -> google.protobuf.Timestamp
	11, // 4: api.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: api.v1.UserOutbox.status:type_name -> api.v1.UserOutboxStatus
	8,  // 6: api.v1.UserOutbox.payload:type_name -> api.v1.User
	11, // 7: api.v1.UserOutbox.created_at:type_name -> google.protobuf.Timestamp
	11, // 8: api.v1.UserOutbox.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 9: api.v1.UserError.error_code:type_name -> api.v1.UserErrorCode
	2,  // 10: api.v1.UserCommandService.RegisterUser:input_type -> api.v1.RegisterUserRequest
	4,  // 11: api.v1.UserCommandInternalService.DeleteUser:input_type -> api.v1.DeleteUserRequest
	6,  // 12: api.v1.UserQueryService.GetAllUsers:input_type -> api.v1.GetAllUsersRequest
	3,  // 13: api.v1.UserCommandService.RegisterUser:output_type -> api.v1.RegisterUserResponse
	5,  // 14: api.v1.UserCommandInternalService.DeleteUser:output_type -> api.v1.DeleteUserResponse
	7,  // 15: api.v1.UserQueryService.GetAllUsers:output_type -> api.v1.GetAllUsersResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_v1_user_proto_init() }
func file_api_v1_user_proto_init() {
	if File_api_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_user_proto_rawDesc), len(file_api_v1_user_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_v1_user_proto_goTypes,
		DependencyIndexes: file_api_v1_user_proto_depIdxs,
		EnumInfos:         file_api_v1_user_proto_enumTypes,
		MessageInfos:      file_api_v1_user_proto_msgTypes,
	}.Build()
	File_api_v1_user_proto = out.File
	file_api_v1_user_proto_goTypes = nil
	file_api_v1_user_proto_depIdxs = nil
}
