// wallet.proto defines service for wallet.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/v1/wallet.proto

package apiv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WalletErrorCode enumerates wallet error code.
type WalletErrorCode int32

const (
	// Default enum code according to
	// https://medium.com/@akhaku/protobuf-definition-best-practices-87f281576f31.
	WalletErrorCode_WALLET_ERROR_CODE_UNSPECIFIED WalletErrorCode = 0
	// Unexpected behavior occured in system.
	WalletErrorCode_WALLET_ERROR_CODE_INTERNAL WalletErrorCode = 1
	// Wallet already exists.
	WalletErrorCode_WALLET_ERROR_CODE_ALREADY_EXISTS WalletErrorCode = 2
	// Wallet instance is nil or empty.
	WalletErrorCode_WALLET_ERROR_CODE_EMPTY_WALLET WalletErrorCode = 3
	// Balance must be numeric and greater than or equal to zero.
	WalletErrorCode_WALLET_ERROR_CODE_INVALID_BALANCE WalletErrorCode = 6
	// Idempotency key is missing.
	WalletErrorCode_WALLET_ERROR_CODE_MISSING_IDEMPOTENCY_KEY WalletErrorCode = 7
	// User is invalid.
	WalletErrorCode_WALLET_ERROR_CODE_INVALID_USER WalletErrorCode = 8
	// Amount must be numeric and greater than zero.
	WalletErrorCode_WALLET_ERROR_CODE_INVALID_AMOUNT WalletErrorCode = 9
	// Sender and receiver must be different.
	WalletErrorCode_WALLET_ERROR_CODE_SAME_ACCOUNT WalletErrorCode = 10
	// Balance is insufficient.
	WalletErrorCode_WALLET_ERROR_CODE_INSUFFICIENT_BALANCE WalletErrorCode = 11
	// Transfer is invalid.
	WalletErrorCode_WALLET_ERROR_CODE_INVALID_TRANSFER WalletErrorCode = 12
)

// Enum value maps for WalletErrorCode.
var (
	WalletErrorCode_name = map[int32]string{
		0:  "WALLET_ERROR_CODE_UNSPECIFIED",
		1:  "WALLET_ERROR_CODE_INTERNAL",
		2:  "WALLET_ERROR_CODE_ALREADY_EXISTS",
		3:  "WALLET_ERROR_CODE_EMPTY_WALLET",
		6:  "WALLET_ERROR_CODE_INVALID_BALANCE",
		7:  "WALLET_ERROR_CODE_MISSING_IDEMPOTENCY_KEY",
		8:  "WALLET_ERROR_CODE_INVALID_USER",
		9:  "WALLET_ERROR_CODE_INVALID_AMOUNT",
		10: "WALLET_ERROR_CODE_SAME_ACCOUNT",
		11: "WALLET_ERROR_CODE_INSUFFICIENT_BALANCE",
		12: "WALLET_ERROR_CODE_INVALID_TRANSFER",
	}
	WalletErrorCode_value = map[string]int32{
		"WALLET_ERROR_CODE_UNSPECIFIED":             0,
		"WALLET_ERROR_CODE_INTERNAL":                1,
		"WALLET_ERROR_CODE_ALREADY_EXISTS":          2,
		"WALLET_ERROR_CODE_EMPTY_WALLET":            3,
		"WALLET_ERROR_CODE_INVALID_BALANCE":         6,
		"WALLET_ERROR_CODE_MISSING_IDEMPOTENCY_KEY": 7,
		"WALLET_ERROR_CODE_INVALID_USER":            8,
		"WALLET_ERROR_CODE_INVALID_AMOUNT":          9,
		"WALLET_ERROR_CODE_SAME_ACCOUNT":            10,
		"WALLET_ERROR_CODE_INSUFFICIENT_BALANCE":    11,
		"WALLET_ERROR_CODE_INVALID_TRANSFER":        12,
	}
)

func (x WalletErrorCode) Enum() *WalletErrorCode {
	p := new(WalletErrorCode)
	*p = x
	return p
}

func (x WalletErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WalletErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_wallet_proto_enumTypes[0].Descriptor()
}

func (WalletErrorCode) Type() protoreflect.EnumType {
	return &file_api_v1_wallet_proto_enumTypes[0]
}

func (x WalletErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WalletErrorCode.Descriptor instead.
func (WalletErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_wallet_proto_rawDescGZIP(), []int{0}
}

// CreateWalletRequest represents request for create wallet.
type CreateWalletRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// wallet represents wallet data.
	Wallet        *Wallet `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletRequest) Reset() {
	*x = CreateWalletRequest{}
	mi := &file_api_v1_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletRequest) ProtoMessage() {}

func (x *CreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWalletRequest) GetWallet() *Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

// CreateWalletResponse represents response from create wallet.
type CreateWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletResponse) Reset() {
	*x = CreateWalletResponse{}
	mi := &file_api_v1_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletResponse) ProtoMessage() {}

func (x *CreateWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletResponse.ProtoReflect.Descriptor instead.
func (*CreateWalletResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_wallet_proto_rawDescGZIP(), []int{1}
}

// TopupWalletRequest represents request for topup wallet.
type TopupWalletRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// topup represents topup data.
	Topup         *Topup `protobuf:"bytes,1,opt,name=topup,proto3" json:"topup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopupWalletRequest) Reset() {
	*x = TopupWalletRequest{}
	mi := &file_api_v1_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopupWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupWalletRequest) ProtoMessage() {}

func (x *TopupWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupWalletRequest.ProtoReflect.Descriptor instead.
func (*TopupWalletRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *TopupWalletRequest) GetTopup() *Topup {
	if x != nil {
		return x.Topup
	}
	return nil
}

// TopupWalletResponse represents response from topup wallet.
type TopupWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopupWalletResponse) Reset() {
	*x = TopupWalletResponse{}
	mi := &file_api_v1_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopupWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupWalletResponse) ProtoMessage() {}

func (x *TopupWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupWalletResponse.ProtoReflect.Descriptor instead.
func (*TopupWalletResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_wallet_proto_rawDescGZIP(), []int{3}
}

// TransferBalanceRequest represents request for transfer balance.
type TransferBalanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// transfer represents transfer data.
	Transfer      *Transfer `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferBalanceRequest) Reset() {
	*x = TransferBalanceRequest{}
	mi := &file_api_v1_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferBalanceRequest) ProtoMessage() {}

func (x *TransferBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferBalanceRequest.ProtoReflect.Descriptor instead.
func (*TransferBalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *TransferBalanceRequest) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

// TransferBalanceResponse represents response from transfer balance.
type TransferBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferBalanceResponse) Reset() {
	*x = TransferBalanceResponse{}
	mi := &file_api_v1_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferBalanceResponse) ProtoMessage() {}

func (x *TransferBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferBalanceResponse.ProtoReflect.Descriptor instead.
func (*TransferBalanceResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_wallet_proto_rawDescGZIP(), []int{5}
}

// Wallet represents wallet.
type Wallet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id represents unique id.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// user_id represents user's id.
	UserId string `protobuf:"bytes,2,opt,name=user_id,proto3" json:"user_id,omitempty"`
	// balance represents balance.
	Balance       string `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_api_v1_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_api_v1_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *Wallet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wallet) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Wallet) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

// Topup represents topup.
type Topup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// wallet_id represents wallet's id.
	WalletId string `protobuf:"bytes,1,opt,name=wallet_id,proto3" json:"wallet_id,omitempty"`
	// amount represents amount.
	Amount        string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topup) Reset() {
	*x = Topup{}
	mi := &file_api_v1_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topup) ProtoMessage() {}

func (x *Topup) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topup.ProtoReflect.Descriptor instead.
func (*Topup) Descriptor() ([]byte, []int) {
	return file_api_v1_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *Topup) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *Topup) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

// Transfer represents transfer.
type Transfer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sender_id represents sender's id.
	SenderId string `protobuf:"bytes,1,opt,name=sender_id,proto3" json:"sender_id,omitempty"`
	// sender_wallet_id represents sender's wallet's id.
	SenderWalletId string `protobuf:"bytes,2,opt,name=sender_wallet_id,proto3" json:"sender_wallet_id,omitempty"`
	// receiver_id represents receiver's id.
	ReceiverId string `protobuf:"bytes,3,opt,name=receiver_id,proto3" json:"receiver_id,omitempty"`
	// receiver_wallet_id represents receiver's wallet's id.
	ReceiverWalletId string `protobuf:"bytes,4,opt,name=receiver_wallet_id,proto3" json:"receiver_wallet_id,omitempty"`
	// amount represents amount.
	Amount        string `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_api_v1_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_api_v1_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *Transfer) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Transfer) GetSenderWalletId() string {
	if x != nil {
		return x.SenderWalletId
	}
	return ""
}

func (x *Transfer) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *Transfer) GetReceiverWalletId() string {
	if x != nil {
		return x.ReceiverWalletId
	}
	return ""
}

func (x *Transfer) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

// WalletError represents message for any error happening in wallet service.
type WalletError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	ErrorCode     WalletErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=api.v1.WalletErrorCode" json:"error_code,omitempty"`
	sizeCache     protoimpl.SizeCache
}

func (x *WalletError) Reset() {
	*x = WalletError{}
	mi := &file_api_v1_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletError) ProtoMessage() {}

func (x *WalletError) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletError.ProtoReflect.Descriptor instead.
func (*WalletError) Descriptor() ([]byte, []int) {
	return file_api_v1_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *WalletError) GetErrorCode() WalletErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return WalletErrorCode_WALLET_ERROR_CODE_UNSPECIFIED
}

var File_api_v1_wallet_proto protoreflect.FileDescriptor

const file_api_v1_wallet_proto_rawDesc = "" +
	"\n" +
	"\x13api/v1/wallet.proto\x12\x06api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"B\n" +
	"\x13CreateWalletRequest\x12+\n" +
	"\x06wallet\x18\x01 \x01(\v2\x0e.api.v1.WalletB\x03\xe0A\x02R\x06wallet\"\x16\n" +
	"\x14CreateWalletResponse\">\n" +
	"\x12TopupWalletRequest\x12(\n" +
	"\x05topup\x18\x01 \x01(\v2\r.api.v1.TopupB\x03\xe0A\x02R\x05topup\"\x15\n" +
	"\x13TopupWalletResponse\"F\n" +
	"\x16TransferBalanceRequest\x12,\n" +
	"\btransfer\x18\x01 \x01(\v2\x10.api.v1.TransferR\btransfer\"\x19\n" +
	"\x17TransferBalanceResponse\"\xe3\x01\n" +
	"\x06Wallet\x12>\n" +
	"\x02id\x18\x01 \x01(\tB.\x92A(J&\"01917a0c-cdfe-74dd-9d95-4d87b5d1f0b8\"\xe0A\x03R\x02id\x12\\\n" +
	"\auser_id\x18\x02 \x01(\tBB\x92A<2\x12Wallet's user's idJ&\"01917a0c-cdfe-7aae-b311-a8c7c32f5c70\"\xe0A\x02R\auser_id\x12;\n" +
	"\abalance\x18\x03 \x01(\tB!\x92A\x1b2\x10Wallet's balanceJ\a\"10.23\"\xe0A\x02R\abalance\"\x99\x01\n" +
	"\x05Topup\x12Y\n" +
	"\twallet_id\x18\x01 \x01(\tB;\x92A52\vWallet's idJ&\"01917a0c-cdfe-701e-9547-ed45a24d7c84\"\xe0A\x02R\twallet_id\x125\n" +
	"\x06amount\x18\x02 \x01(\tB\x1d\x92A\x172\fTopup amountJ\a\"10.23\"\xe0A\x02R\x06amount\"\xea\x03\n" +
	"\bTransfer\x12Y\n" +
	"\tsender_id\x18\x01 \x01(\tB;\x92A52\vSender's idJ&\"01917a10-1086-74a6-8cfb-0074f65bebe3\"\xe0A\x02R\tsender_id\x12p\n" +
	"\x10sender_wallet_id\x18\x02 \x01(\tBD\x92A>2\x14Sender's wallet's idJ&\"01917a10-1086-7faa-9c9e-0bf6a9cf6928\"\xe0A\x02R\x10sender_wallet_id\x12_\n" +
	"\vreceiver_id\x18\x03 \x01(\tB=\x92A72\rReceiver's idJ&\"01917a10-1086-7c94-93c4-32de26621dae\"\xe0A\x02R\vreceiver_id\x12v\n" +
	"\x12receiver_wallet_id\x18\x04 \x01(\tBF\x92A@2\x16Receiver's wallet's idJ&\"01917a10-1086-72df-818a-b72d663fb3b5\"\xe0A\x02R\x12receiver_wallet_id\x128\n" +
	"\x06amount\x18\x05 \x01(\tB \x92A\x1a2\x0fTransfer amountJ\a\"10.23\"\xe0A\x02R\x06amount\"E\n" +
	"\vWalletError\x126\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x17.api.v1.WalletErrorCodeR\terrorCode*\xb6\x03\n" +
	"\x0fWalletErrorCode\x12!\n" +
	"\x1dWALLET_ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aWALLET_ERROR_CODE_INTERNAL\x10\x01\x12$\n" +
	" WALLET_ERROR_CODE_ALREADY_EXISTS\x10\x02\x12\"\n" +
	"\x1eWALLET_ERROR_CODE_EMPTY_WALLET\x10\x03\x12%\n" +
	"!WALLET_ERROR_CODE_INVALID_BALANCE\x10\x06\x12-\n" +
	")WALLET_ERROR_CODE_MISSING_IDEMPOTENCY_KEY\x10\a\x12\"\n" +
	"\x1eWALLET_ERROR_CODE_INVALID_USER\x10\b\x12$\n" +
	" WALLET_ERROR_CODE_INVALID_AMOUNT\x10\t\x12\"\n" +
	"\x1eWALLET_ERROR_CODE_SAME_ACCOUNT\x10\n" +
	"\x12*\n" +
	"&WALLET_ERROR_CODE_INSUFFICIENT_BALANCE\x10\v\x12&\n" +
	"\"WALLET_ERROR_CODE_INVALID_TRANSFER\x10\f2\x9f\x04\n" +
	"\x14WalletCommandService\x12K\n" +
	"\fCreateWallet\x12\x1b.api.v1.CreateWalletRequest\x1a\x1c.api.v1.CreateWalletResponse\"\x00\x12\xb1\x01\n" +
	"\vTopupWallet\x12\x1a.api.v1.TopupWalletRequest\x1a\x1b.api.v1.TopupWalletResponse\"i\x92AE\n" +
	"\x06Wallet*\vTopupWalletr.\n" +
	"\x13\n" +
	"\rAuthorization\x18\x01(\x01\n" +
	"\x17\n" +
	"\x11X-Idempotency-Key\x18\x01(\x01\x82\xd3\xe4\x93\x02\x1b:\x05topup\x1a\x12/v1/wallets/topups\x12\xc6\x01\n" +
	"\x0fTransferBalance\x12\x1e.api.v1.TransferBalanceRequest\x1a\x1f.api.v1.TransferBalanceResponse\"r\x92AH\n" +
	"\x06Wallet*\x0eTransferWalletr.\n" +
	"\x13\n" +
	"\rAuthorization\x18\x01(\x01\n" +
	"\x17\n" +
	"\x11X-Idempotency-Key\x18\x01(\x01\x82\xd3\xe4\x93\x02!:\btransfer\x1a\x15/v1/wallets/transfers\x1a=\x92A:\x128This service provides all use cases to work with wallet.B\x91\x02\x92A\xd1\x01\x12\x97\x01\n" +
	"\n" +
	"Wallet API\"0\n" +
	"\rIndra Saputra\x12\x1fhttps://github.com/indrasaputra*P\n" +
	"\x14BSD 3-Clause License\x128https://github.com/indrasaputra/arjuna/blob/main/LICENSE2\x051.0.0\x1a\x0elocalhost:8000*\x01\x012\x10application/json:\x10application/jsonZ:github.com/indrasaputra/arjuna/service/wallet/api/v1;apiv1b\x06proto3"

var (
	file_api_v1_wallet_proto_rawDescOnce sync.Once
	file_api_v1_wallet_proto_rawDescData []byte
)

func file_api_v1_wallet_proto_rawDescGZIP() []byte {
	file_api_v1_wallet_proto_rawDescOnce.Do(func() {
		file_api_v1_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_wallet_proto_rawDesc), len(file_api_v1_wallet_proto_rawDesc)))
	})
	return file_api_v1_wallet_proto_rawDescData
}

var file_api_v1_wallet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_v1_wallet_proto_goTypes = []any{
	(WalletErrorCode)(0),            // 0: api.v1.WalletErrorCode
	(*CreateWalletRequest)(nil),     // 1: api.v1.CreateWalletRequest
	(*CreateWalletResponse)(nil),    // 2: api.v1.CreateWalletResponse
	(*TopupWalletRequest)(nil),      // 3: api.v1.TopupWalletRequest
	(*TopupWalletResponse)(nil),     // 4: api.v1.TopupWalletResponse
	(*TransferBalanceRequest)(nil),  // 5: api.v1.TransferBalanceRequest
	(*TransferBalanceResponse)(nil), // 6: api.v1.TransferBalanceResponse
	(*Wallet)(nil),                  // 7: api.v1.Wallet
	(*Topup)(nil),                   // 8: api.v1.Topup
	(*Transfer)(nil),                // 9: api.v1.Transfer
	(*WalletError)(nil),             // 10: api.v1.WalletError
}
var file_api_v1_wallet_proto_depIdxs = []int32{
	7, // 0: api.v1.CreateWalletRequest.wallet:type_name -> api.v1.Wallet
	8, // 1: api.v1.TopupWalletRequest.topup:type_name -> api.v1.Topup
	9, // 2: api.v1.TransferBalanceRequest.transfer:type_name -> api.v1.Transfer
	0, // 3: api.v1.WalletError.error_code:type_name -> api.v1.WalletErrorCode
	1, // 4: api.v1.WalletCommandService.CreateWallet:input_type -> api.v1.CreateWalletRequest
	3, // 5: api.v1.WalletCommandService.TopupWallet:input_type -> api.v1.TopupWalletRequest
	5, // 6: api.v1.WalletCommandService.TransferBalance:input_type -> api.v1.TransferBalanceRequest
	2, // 7: api.v1.WalletCommandService.CreateWallet:output_type -> api.v1.CreateWalletResponse
	4, // 8: api.v1.WalletCommandService.TopupWallet:output_type -> api.v1.TopupWalletResponse
	6, // 9: api.v1.WalletCommandService.TransferBalance:output_type -> api.v1.TransferBalanceResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_wallet_proto_init() }
func file_api_v1_wallet_proto_init() {
	if File_api_v1_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_wallet_proto_rawDesc), len(file_api_v1_wallet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_wallet_proto_goTypes,
		DependencyIndexes: file_api_v1_wallet_proto_depIdxs,
		EnumInfos:         file_api_v1_wallet_proto_enumTypes,
		MessageInfos:      file_api_v1_wallet_proto_msgTypes,
	}.Build()
	File_api_v1_wallet_proto = out.File
	file_api_v1_wallet_proto_goTypes = nil
	file_api_v1_wallet_proto_depIdxs = nil
}
