{
 "title": "User Service - Server",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "service", "query": "user-server" }
  ]
 },
 "panels": [
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$service\"}[$__rate_interval])) by (grpc_service, grpc_method)",
     "legendFormat": "{{grpc_service}} - {{grpc_method}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handling_seconds_sum{job=\"$service\"}[$__rate_interval])) by (grpc_service, grpc_method)\n/\nsum(rate(grpc_server_handling_seconds_count{job=\"$service\"}[$__rate_interval])) by (grpc_service, grpc_method)\n",
     "legendFormat": "{{grpc_service}} - {{grpc_method}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$service\",grpc_code!~\"OK|InvalidArgument|AlreadyExists\"}[$__rate_interval])) by (grpc_service, grpc_method)\n/\nsum(rate(grpc_server_handled_total{job=\"$service\"}[$__rate_interval])) by (grpc_service, grpc_method)\n",
     "legendFormat": "{{grpc_service}} - {{grpc_method}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$service\",grpc_code=~\"OK|InvalidArgument|AlreadyExists\"}[$__rate_interval])) by (grpc_service, grpc_method)\n/\nsum(rate(grpc_server_handled_total{job=\"$service\"}[$__rate_interval])) by (grpc_service, grpc_method)\n",
     "legendFormat": "{{grpc_service}} - {{grpc_method}}"
    }
   ]
  },
  {
   "title": "# of Goroutine",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OS Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_threads{job=\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{job=\"$service\"}[$__rate_interval])) by (instance)\n/\nsum(rate(go_gc_duration_seconds_count{job=\"$service\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open File Descriptor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}