// Code generated by MockGen. DO NOT EDIT.
// Source: ./service/wallet/internal/service/wallet_transferer.go
//
// Generated by this command:
//
//	mockgen -source=./service/wallet/internal/service/wallet_transferer.go -destination=./service/wallet/test/mock//service/wallet_transferer.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"

	uow "github.com/indrasaputra/arjuna/pkg/sdk/uow"
	entity "github.com/indrasaputra/arjuna/service/wallet/entity"
)

// MockTransferWallet is a mock of TransferWallet interface.
type MockTransferWallet struct {
	ctrl     *gomock.Controller
	recorder *MockTransferWalletMockRecorder
}

// MockTransferWalletMockRecorder is the mock recorder for MockTransferWallet.
type MockTransferWalletMockRecorder struct {
	mock *MockTransferWallet
}

// NewMockTransferWallet creates a new mock instance.
func NewMockTransferWallet(ctrl *gomock.Controller) *MockTransferWallet {
	mock := &MockTransferWallet{ctrl: ctrl}
	mock.recorder = &MockTransferWalletMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransferWallet) EXPECT() *MockTransferWalletMockRecorder {
	return m.recorder
}

// TransferBalance mocks base method.
func (m *MockTransferWallet) TransferBalance(ctx context.Context, transfer *entity.TransferWallet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferBalance", ctx, transfer)
	ret0, _ := ret[0].(error)
	return ret0
}

// TransferBalance indicates an expected call of TransferBalance.
func (mr *MockTransferWalletMockRecorder) TransferBalance(ctx, transfer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferBalance", reflect.TypeOf((*MockTransferWallet)(nil).TransferBalance), ctx, transfer)
}

// MockWalletTransfererRepository is a mock of WalletTransfererRepository interface.
type MockWalletTransfererRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWalletTransfererRepositoryMockRecorder
}

// MockWalletTransfererRepositoryMockRecorder is the mock recorder for MockWalletTransfererRepository.
type MockWalletTransfererRepositoryMockRecorder struct {
	mock *MockWalletTransfererRepository
}

// NewMockWalletTransfererRepository creates a new mock instance.
func NewMockWalletTransfererRepository(ctrl *gomock.Controller) *MockWalletTransfererRepository {
	mock := &MockWalletTransfererRepository{ctrl: ctrl}
	mock.recorder = &MockWalletTransfererRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletTransfererRepository) EXPECT() *MockWalletTransfererRepositoryMockRecorder {
	return m.recorder
}

// AddWalletBalanceWithTx mocks base method.
func (m *MockWalletTransfererRepository) AddWalletBalanceWithTx(ctx context.Context, tx uow.Tx, id string, amount decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWalletBalanceWithTx", ctx, tx, id, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddWalletBalanceWithTx indicates an expected call of AddWalletBalanceWithTx.
func (mr *MockWalletTransfererRepositoryMockRecorder) AddWalletBalanceWithTx(ctx, tx, id, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWalletBalanceWithTx", reflect.TypeOf((*MockWalletTransfererRepository)(nil).AddWalletBalanceWithTx), ctx, tx, id, amount)
}

// GetUserWalletWithTx mocks base method.
func (m *MockWalletTransfererRepository) GetUserWalletWithTx(ctx context.Context, tx uow.Tx, id, userID string) (*entity.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWalletWithTx", ctx, tx, id, userID)
	ret0, _ := ret[0].(*entity.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWalletWithTx indicates an expected call of GetUserWalletWithTx.
func (mr *MockWalletTransfererRepositoryMockRecorder) GetUserWalletWithTx(ctx, tx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWalletWithTx", reflect.TypeOf((*MockWalletTransfererRepository)(nil).GetUserWalletWithTx), ctx, tx, id, userID)
}
