on:
  workflow_call:
    inputs:
      filters:
        description: The paths to decide if the workflow steps should run.
        required: true
        type: string
      service:
        description: The name of service.
        required: true
        type: string
      dockerfile:
        description: Path to dockerfile
        required: true
        type: string
      platforms:
        description: Platforms to build the target project
        required: false
        type: string
        default: "linux/amd64, linux/arm64, linux/arm/v7"
    
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_TOKEN:
        required: true

jobs:
  build-push-docker:
    name: Build & push ${{ inputs.service }} image
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push ${{ inputs.service }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            docker.io/${{ github.repository }}/${{ inputs.service }}:${{ github.sha }}
            docker.io/${{ github.repository }}/${{ inputs.service }}:latest
