on:
  workflow_call:
    inputs:
      target:
        description: The target project to run the check against.
        required: true
        type: string
      service:
        description: The name of service.
        required: true
        type: string
      cmd:
        description: Service's cmd.
        required: true
        type: string
        default: server
      output_dir:
        description: Output directory of compiled binary.
        required: false
        type: string
        default: deploy/output
      need_go_binary:
        description: Decide if job needs Go binary
        required: false
        type: boolean
        default: false
      dockerfile:
        description: Path to dockerfile
        required: true
        type: string
      platforms:
        description: Platforms to build the target project
        required: false
        type: string
        default: "linux/amd64,linux/arm64,linux/arm/v7"

    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_TOKEN:
        required: true

jobs:
  build-push-docker:
    name: Build & push ${{ inputs.service }}-${{ inputs.cmd }} image
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            docker.io/${{ github.repository }}-${{ inputs.service }}-${{ inputs.cmd }}
          tags: |
            type=raw,value=${{ github.sha }}
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Download go binary
        if: ${{ inputs.need_go_binary }}
        uses: actions/download-artifact@v4
        with:
          name: go-binary-${{ inputs.service }}-${{ github.sha }}
          path: ${{ inputs.target }}/${{ inputs.output_dir }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push ${{ inputs.service }}-${{ inputs.cmd }}
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: ${{ steps.docker-metadata.outputs.tags }}
