on:
  workflow_call:
    inputs:
      filters:
        description: The paths to decide if the workflow steps should run.
        required: true
        type: string
      target:
        description: The target project to run the check against.
        required: true
        type: string
      service:
        description: The name of service.
        required: true
        type: string
      output_dir:
        description: Output directory of compiled binary.
        required: false
        type: string
        default: deploy/output
      need_go_binary:
        description: Decide if job needs Go binary
        required: false
        type: boolean
        default: false
      dockerfile:
        description: Path to dockerfile
        required: true
        type: string
      platforms:
        description: Platforms to build the target project
        required: false
        type: string
        default: "linux/amd64, linux/arm64, linux/arm/v7"
    
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_TOKEN:
        required: true

jobs:
  compile-binary:
    name: Compile go binary
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.17.x
      - name: Clone repository
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-module-${{ github.repository }}-${{ inputs.target }}-${{ github.sha }}
          restore-keys: |
            go-module-${{ github.repository }}-${{ inputs.target }}-${{ github.sha }}
      - name: Compile go binary
        run: |
          make compile svc=${{ inputs.service }}
      - name: Upload go binary
        uses: actions/upload-artifact@v3
        with:
          name: go-binary-${{ inputs.service }}-${{ github.sha }}
          path: ${{ inputs.target }}/${{ inputs.output_dir }}
          retention-days: 1

  build-push-docker:
    name: Build & push ${{ inputs.service }} image
    needs: [compile-binary]
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ github.repository }}-${{ inputs.service }}
          tags: |
            type=sha,format=long
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Download go binary
        if: ${{ inputs.need_go_binary }}
        uses: actions/download-artifact@v3
        with:
          name: go-binary-${{ inputs.service }}-${{ github.sha }}
          path: ${{ inputs.target }}/${{ inputs.output_dir }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push ${{ inputs.service }}
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: ${{ steps.docker-metadata.outputs.tags }}
