on:
  workflow_call:
    inputs:
      filters:
        description: The paths to decide if the workflow steps should run.
        required: true
        type: string
      target:
        description: The target project to run the check against.
        required: true
        type: string

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Filter paths
        uses: dorny/paths-filter@v2
        id: filter
        with:
          initial-fetch-depth: 10
          filters: ${{ inputs.filters }}
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17.x
      - name: Lint using golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          args: --config=${GITHUB_WORKSPACE}/.golangci.yml
          working-directory: ${{ inputs.target }}
