name: Auth service - CI

on:
  push:
    paths:
      - ".github/workflows/reusable-general-quality-ci.yml"
      - ".github/workflows/reusable-go-build-ci.yml"
      - ".github/workflows/reusable-go-quality-ci.yml"
      - ".github/workflows/service-auth.yml"
      - "pkg/**"
      - "openapiv2/**"
      - "proto/**"
      - "tool/**"
      - "gateway/**"
      - "service/auth/**"
  pull_request:
    paths:
      - ".github/workflows/reusable-general-quality-ci.yml"
      - ".github/workflows/reusable-go-build-ci.yml"
      - ".github/workflows/reusable-go-quality-ci.yml"
      - ".github/workflows/service-auth.yml"
      - "pkg/**"
      - "openapiv2/**"
      - "proto/**"
      - "tool/**"
      - "gateway/**"
      - "service/auth/**"

jobs:
  change-check:
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      has-change: ${{ steps.filter.outputs.changed }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Check path filters
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
            - '.github/workflows/reusable-general-quality-ci.yml'
            - '.github/workflows/reusable-go-build-ci.yml'
            - '.github/workflows/reusable-go-quality-ci.yml'
            - '.github/workflows/service-auth.yml'
            - 'pkg/**'
            - 'openapiv2/**'
            - 'proto/**'
            - 'tool/**'
            - 'gateway/**'
            - 'service/auth/**'

  general-quality-check:
    name: General quality check
    uses: indrasaputra/arjuna/.github/workflows/reusable-general-quality-ci.yml@main

  go-code-quality:
    name: Go code quality check
    needs: [change-check]
    if: ${{ needs.change-check.outputs.has-change == 'true' }}
    uses: indrasaputra/arjuna/.github/workflows/reusable-go-quality-ci.yml@main
    with:
      target: service/auth

  build-push-docker:
    name: Build and push docker
    needs: [general-quality-check, go-code-quality, change-check]
    if: ${{ needs.change-check.outputs.has-change == 'true' }}
    uses: indrasaputra/arjuna/.github/workflows/reusable-go-build-ci.yml@main
    with:
      target: service/auth
      service: auth
      dockerfile: ./service/auth/dockerfile/auth.dockerfile
      need_go_binary: true
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
