name: Wallet service - CI

on:
  push:
    paths:
      - ".github/workflows/reusable-general-quality-ci.yml"
      - ".github/workflows/reusable-go-build-ci.yml"
      - ".github/workflows/reusable-go-quality-ci.yml"
      - ".github/workflows/service-wallet.yml"
      - "pkg/**"
      - "openapiv2/**"
      - "proto/**"
      - "tool/**"
      - "gateway/**"
      - "service/wallet/**"
  pull_request:
    paths:
      - ".github/workflows/reusable-general-quality-ci.yml"
      - ".github/workflows/reusable-go-build-ci.yml"
      - ".github/workflows/reusable-go-quality-ci.yml"
      - ".github/workflows/service-wallet.yml"
      - "pkg/**"
      - "openapiv2/**"
      - "proto/**"
      - "tool/**"
      - "gateway/**"
      - "service/wallet/**"

jobs:
  change-check:
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      has-change: ${{ steps.filter.outputs.changed }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Check path filters
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
            - '.github/workflows/reusable-general-quality-ci.yml'
            - '.github/workflows/reusable-go-build-ci.yml'
            - '.github/workflows/reusable-go-quality-ci.yml'
            - '.github/workflows/service-wallet.yml'
            - 'pkg/**'
            - 'openapiv2/**'
            - 'proto/**'
            - 'tool/**'
            - 'gateway/**'
            - 'service/wallet/**'

  general-quality-check:
    name: General quality check
    uses: ./.github/workflows/reusable-general-quality-ci.yml

  go-code-quality:
    name: Go code quality check
    needs: [change-check]
    if: ${{ needs.change-check.outputs.has-change == 'true' }}
    uses: ./.github/workflows/reusable-go-quality-ci.yml
    with:
      target: service/wallet
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  compile-binary:
    name: Compile binary
    needs: [general-quality-check, go-code-quality, change-check]
    if: ${{ needs.change-check.outputs.has-change == 'true' }}
    uses: ./.github/workflows/reusable-go-compile-ci.yml
    with:
      target: service/wallet
      service: wallet

  build-push-docker:
    name: Build and push docker
    needs: [compile-binary]
    if: ${{ needs.change-check.outputs.has-change == 'true' }}
    strategy:
      matrix:
        cmd: [server]
    uses: ./.github/workflows/reusable-go-build-ci.yml
    with:
      target: service/wallet
      service: wallet
      dockerfile: ./service/wallet/dockerfile/wallet.dockerfile
      need_go_binary: true
      cmd: ${{ matrix.cmd }}
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
