name: User service - CI

on:
  push:
    paths:
      - '.github/workflows/reusable-general-ci.yml'
      - '.github/workflows/reusable-go-ci.yml'
      - '.github/workflows/service-user.yml'
      - 'pkg/**'
      - 'openapiv2/**'
      - 'proto/**'
      - 'tool/**'
      - 'gateway/**'
      - 'service/user/**'
  pull_request:
    paths:
      - '.github/workflows/reusable-general-ci.yml'
      - '.github/workflows/reusable-go-ci.yml'
      - '.github/workflows/service-user.yml'
      - 'pkg/**'
      - 'openapiv2/**'
      - 'proto/**'
      - 'tool/**'
      - 'gateway/**'
      - 'service/user/**'

jobs:
  general-quality-check:
    name: General quality check
    uses: indrasaputra/arjuna/.github/workflows/reusable-general-quality-ci.yml@cicd-pipeline

  go-code-quality:
    name: Go code quality check
    uses: indrasaputra/arjuna/.github/workflows/reusable-go-quality-ci.yml@cicd-pipeline
    with:
      filters: |
        changed:
          - '.github/workflows/reusable-general-ci.yml'
          - '.github/workflows/reusable-go-ci.yml'
          - '.github/workflows/service-user.yml'
          - 'pkg/**'
          - 'openapiv2/**'
          - 'proto/**'
          - 'tool/**'
          - 'gateway/**'
          - 'service/user/**'
      target: service/user

  go-compile-binary:
    name: Compile app binary
    needs: [general-quality-check, go-code-quality]
    uses: indrasaputra/arjuna/.github/workflows/reusable-go-compile-ci.yml@cicd-pipeline
    with:
      filters: |
        changed:
          - '.github/workflows/reusable-general-ci.yml'
          - '.github/workflows/reusable-go-ci.yml'
          - '.github/workflows/service-user.yml'
          - 'pkg/**'
          - 'openapiv2/**'
          - 'proto/**'
          - 'tool/**'
          - 'gateway/**'
          - 'service/user/**'
      target: service/user
      svc: user
      need_go_binary: true
      dockerfile: ./service/user/user.dockerfile
