name: Test

on: [push, pull_request]

jobs:
  pr-title-check:
    name: Check PR title
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      # Refer to https://www.conventionalcommits.org/en/v1.0.0/ for commit message convention.
      - uses: amannn/action-semantic-pull-request@v3.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  unit-test:
    name: Unit test and coverage
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17.x
      - name: Clone repository
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-module-${{ github.repository }}-${{ github.sha }}
          restore-keys: |
            go-module-${{ github.repository }}-${{ github.sha }}
      - name: Run unit test and coverage
        run: make test.cover
      - name: Push coverage result to Codecov
        uses: codecov/codecov-action@v1.0.13
