// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createTransaction = `-- name: CreateTransaction :exec
INSERT INTO transactions (id, sender_id, receiver_id, amount, created_at, updated_at, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateTransactionParams struct {
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Amount     decimal.Decimal
	ID         uuid.UUID
	SenderID   uuid.UUID
	ReceiverID uuid.UUID
	CreatedBy  uuid.UUID
	UpdatedBy  uuid.UUID
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) error {
	_, err := q.db.Exec(ctx, createTransaction,
		arg.ID,
		arg.SenderID,
		arg.ReceiverID,
		arg.Amount,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	return err
}

const hardDeleteAllTransactions = `-- name: HardDeleteAllTransactions :exec
DELETE FROM transactions
`

func (q *Queries) HardDeleteAllTransactions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, hardDeleteAllTransactions)
	return err
}
